name: Build scan Service (Maven + Docker + ECR Push)

on:
  push:
    branches: [ main ]
    paths:
      - "scan-service/**"

jobs:
  build:
    runs-on: self-hosted

    env:
      IMAGE_NAME: 143471984294.dkr.ecr.us-east-1.amazonaws.com/my-ecr-dev:latest-scan
      AWS_REGION: us-east-1
      AWS_ACCOUNT_ID: 143471984294

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -f scan-service/pom.xml clean package -DskipTests

      - name: Docker Version
        run: docker --version

      - name: Build Docker Image
        run: |
          sudo docker build -t $IMAGE_NAME scan-service
          echo "Docker image $IMAGE_NAME built successfully"

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Push Docker Image to ECR
        run: |
          sudo docker push $IMAGE_NAME
          echo "Docker image pushed to ECR successfully"

      - name: Cleanup disk space
        run: |
          sudo rm -rf /home/ubuntu/actions-runner/_work/*
